export const APP_INIT = 'APP_INIT';
export const APP_SHOW_SIDEBAR = 'APP_SHOW_SIDEBAR';
export const APP_HIDE_SIDEBAR = 'APP_HIDE_SIDEBAR';

export const USER_LOGGEDIN = 'USER_LOGGEDIN';

export const TASK_MANAGER_LOAD_ALL = 'TASK_MANAGER_LOAD_ALL';
export const TASK_MANAGER_SET_ACTIVE = 'TASK_MANAGER_SET_ACTIVE';
export const TASK_MANAGER_UPDATE_TASK = 'TASK_MANAGER_UPDATE_TASK';

export const USERS_LOAD_ALL = 'USERS_LOAD_ALL';
