export const APP_INIT = 'APP_INIT';

export const USER_LOGGEDIN = 'USER_LOGGEDIN';

export const TASK_MANAGER_LOAD_ALL = 'TASK_MANAGER_LOAD_ALL';
export const TASK_MANAGER_SET_ACTIVE = 'TASK_MANAGER_SET_ACTIVE';
